import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Good Source Chocolates",
    price: 68.0,
    image: "/premium-chocolate-bar-package.jpg",
    category: "Chocolate",
    description: "Premium organic chocolate bars made from the finest cocoa beans",
    rating: 4.8,
    inStock: true,
    stock: 25,
    popularity: 95,
    createdAt: "2024-01-15",
  },
  {
    id: "2",
    name: "Dark Chocolate Deluxe",
    price: 45.0,
    image: "/dark-chocolate-premium-package.jpg",
    category: "Chocolate",
    description: "Rich 85% dark chocolate with intense flavor",
    rating: 4.9,
    inStock: true,
    stock: 18,
    popularity: 88,
    createdAt: "2024-01-20",
  },
  {
    id: "3",
    name: "Coconut Chips",
    price: 18.0,
    image: "/coconut-chips-healthy-snack.jpg",
    category: "Chips",
    description: "Crispy toasted coconut chips, naturally sweet",
    rating: 4.6,
    inStock: true,
    stock: 42,
    popularity: 76,
    createdAt: "2024-02-01",
  },
  {
    id: "4",
    name: "Artisan Nuts Mix",
    price: 32.0,
    image: "/premium-mixed-nuts-package.jpg",
    category: "Nuts",
    description: "Carefully selected premium nuts and dried fruits",
    rating: 4.7,
    inStock: true,
    stock: 33,
    popularity: 82,
    createdAt: "2024-01-28",
  },
  {
    id: "5",
    name: "Organic Granola",
    price: 24.0,
    image: "/organic-granola-healthy-breakfast.jpg",
    category: "Granola",
    description: "Homemade style granola with honey and oats",
    rating: 4.5,
    inStock: true,
    stock: 28,
    popularity: 71,
    createdAt: "2024-02-05",
  },
  {
    id: "6",
    name: "Sweet Protein Bars",
    price: 36.0,
    image: "/protein-bars-healthy-snack.jpg",
    category: "Bars",
    description: "High-protein bars with natural sweeteners",
    rating: 4.4,
    inStock: true,
    stock: 15,
    popularity: 68,
    createdAt: "2024-02-10",
  },
  {
    id: "7",
    name: "Spicy Jalapeño Chips",
    price: 22.0,
    image: "/spicy-jalapeno-chips-bag.jpg",
    category: "Chips",
    description: "Crunchy chips with a perfect kick of jalapeño heat",
    rating: 4.3,
    inStock: true,
    stock: 38,
    popularity: 74,
    createdAt: "2024-02-12",
  },
  {
    id: "8",
    name: "Honey Roasted Almonds",
    price: 28.0,
    image: "/honey-roasted-almonds-package.jpg",
    category: "Nuts",
    description: "Sweet and crunchy honey-glazed almonds",
    rating: 4.6,
    inStock: true,
    stock: 31,
    popularity: 79,
    createdAt: "2024-02-08",
  },
  {
    id: "9",
    name: "Milk Chocolate Truffles",
    price: 52.0,
    image: "/luxury-milk-chocolate-truffles-box.jpg",
    category: "Chocolate",
    description: "Luxurious handcrafted milk chocolate truffles",
    rating: 4.9,
    inStock: true,
    stock: 12,
    popularity: 92,
    createdAt: "2024-02-14",
  },
  {
    id: "10",
    name: "Cinnamon Granola Clusters",
    price: 26.0,
    image: "/cinnamon-granola-clusters-bag.jpg",
    category: "Granola",
    description: "Crispy granola clusters with warm cinnamon spice",
    rating: 4.5,
    inStock: true,
    stock: 24,
    popularity: 73,
    createdAt: "2024-02-16",
  },
  {
    id: "11",
    name: "Energy Boost Bars",
    price: 42.0,
    image: "/energy-boost-protein-bars-pack.jpg",
    category: "Bars",
    description: "High-energy bars packed with superfoods and protein",
    rating: 4.7,
    inStock: true,
    stock: 19,
    popularity: 85,
    createdAt: "2024-02-18",
  },
  {
    id: "12",
    name: "Sea Salt Caramel Chips",
    price: 25.0,
    image: "/sea-salt-caramel-chips-premium-bag.jpg",
    category: "Chips",
    description: "Sweet and salty caramel-flavored gourmet chips",
    rating: 4.4,
    inStock: true,
    stock: 35,
    popularity: 77,
    createdAt: "2024-02-20",
  },
  {
    id: "13",
    name: "Mixed Berry Granola",
    price: 29.0,
    image: "/mixed-berry-granola-healthy-breakfast.jpg",
    category: "Granola",
    description: "Antioxidant-rich granola with real dried berries",
    rating: 4.6,
    inStock: true,
    stock: 27,
    popularity: 80,
    createdAt: "2024-02-22",
  },
  {
    id: "14",
    name: "Cashew Butter Bars",
    price: 38.0,
    image: "/cashew-butter-protein-bars-healthy.jpg",
    category: "Bars",
    description: "Creamy cashew butter bars with natural sweetness",
    rating: 4.5,
    inStock: true,
    stock: 21,
    popularity: 75,
    createdAt: "2024-02-24",
  },
  {
    id: "15",
    name: "White Chocolate Macadamia",
    price: 58.0,
    image: "/white-chocolate-macadamia-premium-bar.jpg",
    category: "Chocolate",
    description: "Creamy white chocolate with premium macadamia nuts",
    rating: 4.8,
    inStock: true,
    stock: 16,
    popularity: 89,
    createdAt: "2024-02-26",
  },
  {
    id: "16",
    name: "Wasabi Peas",
    price: 16.0,
    image: "/wasabi-peas-spicy-snack-bag.jpg",
    category: "Nuts",
    description: "Crunchy green peas with a spicy wasabi coating",
    rating: 4.2,
    inStock: true,
    stock: 44,
    popularity: 65,
    createdAt: "2024-02-28",
  },
]

export const categories = ["All", "Chocolate", "Chips", "Nuts", "Granola", "Bars"]
